# Generated by Django 5.0.2 on 2026-08-28 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecoles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/eleves/')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='ecoles.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='ecoles.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='ecoles.ecole')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='ecoles.niveau')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='bulletins/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='ecoles.anneescolaire')),
                ('upload_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.eleve')),
            ],
            options={
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='MasquageColonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_num', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('periode', 'Période'), ('examen', 'Examen')], max_length=10)),
                ('periode_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('masque', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.anneescolaire')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masquages_colonnes', to='eleves.eleve')),
            ],
            options={
                'indexes': [models.Index(fields=['eleve', 'annee_scolaire', 'cours', 'cycle_num'], name='eleves_masq_eleve_i_c110c4_idx')],
                'unique_together': {('eleve', 'annee_scolaire', 'cours', 'cycle_num', 'type', 'periode_num')},
            },
        ),
        migrations.CreateModel(
            name='MasquageEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masque', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masquages', to='eleves.eleve')),
                ('evaluation_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.evaluationconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['eleve', 'annee_scolaire', 'evaluation_config'], name='eleves_masq_eleve_i_52dc78_idx')],
                'unique_together': {('eleve', 'annee_scolaire', 'evaluation_config')},
            },
        ),
        migrations.CreateModel(
            name='ParcoursEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_actuel', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='ecoles.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='eleves.eleve')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.niveau')),
            ],
            options={
                'ordering': ['-annee_scolaire__annee'],
                'indexes': [models.Index(fields=['eleve', 'annee_scolaire'], name='eleves_parc_eleve_i_4a64bd_idx'), models.Index(fields=['ecole', 'annee_scolaire'], name='eleves_parc_ecole_i_715a29_idx')],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
