# Generated by Django 5.0.2 on 2026-08-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0009_anneescolaire_ecoles_anne_est_act_4e31d0_idx_and_more'),
        ('eleves', '0002_eleve_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasquageEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masque', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masquages', to='eleves.eleve')),
                ('evaluation_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.evaluationconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['eleve', 'annee_scolaire', 'evaluation_config'], name='eleves_masq_eleve_i_52dc78_idx')],
                'unique_together': {('eleve', 'annee_scolaire', 'evaluation_config')},
            },
        ),
        migrations.CreateModel(
            name='ParcoursEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_actuel', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='ecoles.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='eleves.eleve')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.niveau')),
            ],
            options={
                'ordering': ['-annee_scolaire__annee'],
                'indexes': [models.Index(fields=['eleve', 'annee_scolaire'], name='eleves_parc_eleve_i_4a64bd_idx'), models.Index(fields=['ecole', 'annee_scolaire'], name='eleves_parc_ecole_i_715a29_idx')],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
