# Generated by Django 5.0.2 on 2026-08-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0009_anneescolaire_ecoles_anne_est_act_4e31d0_idx_and_more'),
        ('eleves', '0003_masquageevaluation_parcourseleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasquageColonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_num', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('periode', 'Période'), ('examen', 'Examen')], max_length=10)),
                ('periode_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('masque', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.anneescolaire')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoles.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masquages_colonnes', to='eleves.eleve')),
            ],
            options={
                'indexes': [models.Index(fields=['eleve', 'annee_scolaire', 'cours', 'cycle_num'], name='eleves_masq_eleve_i_c110c4_idx')],
                'unique_together': {('eleve', 'annee_scolaire', 'cours', 'cycle_num', 'type', 'periode_num')},
            },
        ),
    ]
