# Generated by Django 5.0.2 on 2026-08-28 08:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('est_reference', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type_gestion', models.CharField(choices=[('public', 'Publique'), ('prive', 'Privée'), ('conventionne', 'Conventionné')], default='public', max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('est_reference', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultatAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_points_possibles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pourcentage_general', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_num', models.PositiveSmallIntegerField()),
                ('total_points_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_points_possibles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moyenne_sur_20', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('est_reference', models.BooleanField(default=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='ecoles.classe')),
            ],
        ),
        migrations.CreateModel(
            name='CycleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cycle', models.CharField(choices=[('trimestre', 'Trimestriel'), ('semestre', 'Semestriel')], default='trimestre', max_length=20)),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_evaluation', to='ecoles.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_reference', models.BooleanField(default=False)),
                ('classes', models.ManyToManyField(blank=True, related_name='domaines', to='ecoles.classe')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='ecoles.ecole')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='ecoles.domaine'),
        ),
        migrations.AddField(
            model_name='cours',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='ecoles.ecole'),
        ),
        migrations.AddField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecoles.ecole'),
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=9, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_actuelle', models.BooleanField(default=False)),
                ('ecoles', models.ManyToManyField(related_name='annees_scolaires', to='ecoles.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_num', models.PositiveSmallIntegerField()),
                ('periode_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('periode', 'Période'), ('examen', 'Examen')], max_length=10)),
                ('points_max', models.PositiveIntegerField(default=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('cycle_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ecoles.cycleevaluation')),
            ],
            options={
                'ordering': ['cycle_num', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_obtenus', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_resultats', to='ecoles.anneescolaire')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_resultats', to='ecoles.cours')),
            ],
        ),
    ]
