# Generated by Django 5.0.2 on 2026-08-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecoles', '0001_initial'),
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresultat',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_resultats', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='evaluationresultat',
            name='evaluation_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='ecoles.evaluationconfig'),
        ),
        migrations.AddField(
            model_name='evaluationresultat',
            name='saisie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_resultats_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveau',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='ecoles.ecole'),
        ),
        migrations.AddField(
            model_name='domaine',
            name='niveaux',
            field=models.ManyToManyField(blank=True, related_name='domaines', to='ecoles.niveau'),
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='ecoles.niveau'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecoles.niveau'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecoles', to='ecoles.province'),
        ),
        migrations.AddField(
            model_name='resultatannuel',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_annuels', to='ecoles.anneescolaire'),
        ),
        migrations.AddField(
            model_name='resultatannuel',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_annuels', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='resultatcycle',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_cycles', to='ecoles.anneescolaire'),
        ),
        migrations.AddField(
            model_name='resultatcycle',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_cycles', to='ecoles.cours'),
        ),
        migrations.AddField(
            model_name='resultatcycle',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_cycles', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux', to='ecoles.section'),
        ),
        migrations.AddIndex(
            model_name='anneescolaire',
            index=models.Index(fields=['est_actuelle'], name='ecoles_anne_est_act_4e31d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationconfig',
            unique_together={('cycle_evaluation', 'cycle_num', 'periode_num', 'type')},
        ),
        migrations.AddIndex(
            model_name='evaluationresultat',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='ecoles_eval_eleve_i_c22f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresultat',
            index=models.Index(fields=['cours', 'annee_scolaire'], name='ecoles_eval_cours_i_ac1f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresultat',
            index=models.Index(fields=['eleve', 'cours', 'annee_scolaire'], name='ecoles_eval_eleve_i_e5442c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationresultat',
            unique_together={('eleve', 'cours', 'annee_scolaire', 'evaluation_config')},
        ),
        migrations.AddIndex(
            model_name='domaine',
            index=models.Index(fields=['ecole', 'est_reference'], name='ecoles_doma_ecole_i_fecd08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domaine',
            unique_together={('nom', 'ecole')},
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['niveau', 'classe', 'ecole', 'est_reference'], name='ecoles_cour_niveau__a82741_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('nom', 'niveau', 'classe', 'domaine', 'ecole')},
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['niveau', 'ecole', 'est_reference'], name='ecoles_clas_niveau__7853b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'niveau', 'ecole')},
        ),
        migrations.AddIndex(
            model_name='ecole',
            index=models.Index(fields=['province', 'est_active'], name='ecoles_ecol_provinc_e2c93b_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatannuel',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='ecoles_resu_eleve_i_f9e4df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultatannuel',
            unique_together={('eleve', 'annee_scolaire')},
        ),
        migrations.AddIndex(
            model_name='resultatcycle',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='ecoles_resu_eleve_i_3606ab_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatcycle',
            index=models.Index(fields=['cours', 'annee_scolaire'], name='ecoles_resu_cours_i_d53b02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultatcycle',
            unique_together={('eleve', 'cours', 'annee_scolaire', 'cycle_num')},
        ),
        migrations.AddIndex(
            model_name='niveau',
            index=models.Index(fields=['ecole', 'est_reference'], name='ecoles_nive_ecole_i_b20bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='niveau',
            index=models.Index(fields=['section'], name='ecoles_nive_section_65644b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='niveau',
            unique_together={('nom', 'ecole', 'section')},
        ),
    ]
