# Generated by Django 5.0.2 on 2026-07-28 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecoles', '0001_initial'),
        ('eleves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresultat',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_resultats', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='evaluationresultat',
            name='evaluation_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='ecoles.evaluationconfig'),
        ),
        migrations.AddField(
            model_name='evaluationresultat',
            name='saisie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_resultats_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveau',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='ecoles.ecole'),
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='ecoles.niveau'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecoles.niveau'),
        ),
        migrations.AddField(
            model_name='resultatannuel',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_annuels', to='ecoles.anneescolaire'),
        ),
        migrations.AddField(
            model_name='resultatannuel',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_annuels', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='resultatcycle',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_cycles', to='ecoles.anneescolaire'),
        ),
        migrations.AddField(
            model_name='resultatcycle',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_cycles', to='ecoles.cours'),
        ),
        migrations.AddField(
            model_name='resultatcycle',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_cycles', to='eleves.eleve'),
        ),
        migrations.AlterUniqueTogether(
            name='domaine',
            unique_together={('nom', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationconfig',
            unique_together={('cycle_evaluation', 'cycle_num', 'periode_num', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationresultat',
            unique_together={('eleve', 'cours', 'annee_scolaire', 'evaluation_config')},
        ),
        migrations.AlterUniqueTogether(
            name='niveau',
            unique_together={('nom', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('nom', 'niveau', 'classe', 'domaine', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'niveau', 'ecole')},
        ),
        migrations.AlterUniqueTogether(
            name='resultatannuel',
            unique_together={('eleve', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='resultatcycle',
            unique_together={('eleve', 'cours', 'annee_scolaire', 'cycle_num')},
        ),
    ]
