# Generated by Django 5.0.2 on 2026-07-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='est_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classe',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cours',
            name='est_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domaine',
            name='est_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='niveau',
            name='est_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='niveau',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecoles.ecole'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='ecoles.ecole'),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='ecoles.ecole'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='ecoles.ecole'),
        ),
    ]
