# Generated by Django 5.0.2 on 2026-08-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='ecoles.cours'),
        ),
    ]
