# Generated by Django 5.0.2 on 2026-08-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0003_cours_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='reference',
        ),
    ]
