# Generated by Django 5.0.2 on 2026-07-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0003_classe_description_classe_est_reference_classe_ordre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='domaines', to='ecoles.classe'),
        ),
        migrations.AddField(
            model_name='domaine',
            name='niveaux',
            field=models.ManyToManyField(blank=True, related_name='domaines', to='ecoles.niveau'),
        ),
    ]
