# Generated by Django 5.0.2 on 2026-07-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0006_province_alter_ecole_province'),
    ]

    operations = [
    ]
