# Generated by Django 5.0.2 on 2026-08-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0005_auto_20260831_2223'),
        ('ecoles', '0006_auto_20260831_2257'),
    ]

    operations = [
    ]
