# Generated by Django 5.0.2 on 2026-07-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0007_migrate_province_data'),
    ]

    operations = [
    ]
