# Generated by Django 5.0.2 on 2026-08-03 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0008_prepare_province'),
        ('eleves', '0002_eleve_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anneescolaire',
            index=models.Index(fields=['est_actuelle'], name='ecoles_anne_est_act_4e31d0_idx'),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['niveau', 'ecole', 'est_reference'], name='ecoles_clas_niveau__7853b3_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['niveau', 'classe', 'ecole', 'est_reference'], name='ecoles_cour_niveau__a82741_idx'),
        ),
        migrations.AddIndex(
            model_name='domaine',
            index=models.Index(fields=['ecole', 'est_reference'], name='ecoles_doma_ecole_i_fecd08_idx'),
        ),
        migrations.AddIndex(
            model_name='ecole',
            index=models.Index(fields=['province', 'est_active'], name='ecoles_ecol_provinc_e2c93b_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresultat',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='ecoles_eval_eleve_i_c22f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresultat',
            index=models.Index(fields=['cours', 'annee_scolaire'], name='ecoles_eval_cours_i_ac1f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresultat',
            index=models.Index(fields=['eleve', 'cours', 'annee_scolaire'], name='ecoles_eval_eleve_i_e5442c_idx'),
        ),
        migrations.AddIndex(
            model_name='niveau',
            index=models.Index(fields=['ecole', 'est_reference'], name='ecoles_nive_ecole_i_b20bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatannuel',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='ecoles_resu_eleve_i_f9e4df_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatcycle',
            index=models.Index(fields=['eleve', 'annee_scolaire'], name='ecoles_resu_eleve_i_3606ab_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatcycle',
            index=models.Index(fields=['cours', 'annee_scolaire'], name='ecoles_resu_cours_i_d53b02_idx'),
        ),
    ]
