# Generated by Django 5.0.2 on 2026-08-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0009_anneescolaire_ecoles_anne_est_act_4e31d0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='type_gestion',
            field=models.CharField(choices=[('public', 'Publique'), ('prive', 'Privée'), ('conventionne', 'Conventionné')], default='public', max_length=20),
        ),
    ]
