# Generated by Django 5.0.2 on 2026-08-26 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0010_ecole_type_gestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_reference', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='niveau',
            name='a_section',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='niveau',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux', to='ecoles.option'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_reference', models.BooleanField(default=False)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ecoles.ecole')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ecoles.section'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux', to='ecoles.section'),
        ),
        migrations.AddIndex(
            model_name='niveau',
            index=models.Index(fields=['section', 'option'], name='ecoles_nive_section_f9289e_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['ecole', 'est_reference'], name='ecoles_sect_ecole_i_927709_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('nom', 'ecole')},
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['section', 'est_reference'], name='ecoles_opti_section_e6bdd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('nom', 'section')},
        ),
    ]
