# Generated by Django 5.0.2 on 2026-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0011_option_niveau_a_section_niveau_option_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['section__ordre', 'ordre', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.RemoveIndex(
            model_name='option',
            name='ecoles_opti_section_e6bdd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='ecoles_sect_ecole_i_927709_idx',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='niveau',
            name='a_section',
        ),
        migrations.RemoveField(
            model_name='option',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='option',
            name='est_reference',
        ),
        migrations.AddField(
            model_name='option',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='option',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='section',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='section',
            name='est_reference',
        ),
    ]
