# Generated by Django 5.0.2 on 2026-08-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0012_alter_option_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='niveau',
            unique_together={('nom', 'ecole', 'section', 'option')},
        ),
    ]
