# Generated by Django 5.0.2 on 2026-08-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecoles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='classe_affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='ecoles.classe', verbose_name="Classe d'affectation"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ecole_affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoles.ecole', verbose_name="École d'affectation"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='niveau_affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='ecoles.niveau', verbose_name="Niveau d'affectation"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='province_affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ecoles.province', verbose_name="Province d'affectation"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['utilisateur', 'timestamp'], name='accounts_au_utilisa_5e6801_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='accounts_au_action_11cc52_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='accounts_au_model_n_76c60d_idx'),
        ),
    ]
