# Generated by Django 5.0.2 on 2026-07-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('ecoles', '0005_classe_deleted_at_cours_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='classe_affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='ecoles.classe', verbose_name="Classe d'affectation"),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='niveau_affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='ecoles.niveau', verbose_name="Niveau d'affectation"),
        ),
    ]
