# Generated by Django 5.0.2 on 2026-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MINISTRE', 'Ministre'), ('INSPECTEUR', 'Inspecteur'), ('AGENT', 'Agent'), ('ENSEIGNANT', 'Enseignant'), ('PARENT', 'Parent'), ('PROVED', 'Directeur Provincial'), ('EDITOR', 'Éditeur')], default='ADMIN', max_length=20),
        ),
    ]
