# Generated by Django 5.0.2 on 2026-07-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utilisateur_classe_affectation_and_more'),
        ('eleves', '0002_eleve_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='eleves_associes',
            field=models.ManyToManyField(blank=True, related_name='parents', to='eleves.eleve', verbose_name='Élèves associés'),
        ),
    ]
