# Generated by Django 5.0.2 on 2026-07-31 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_utilisateur_eleves_associes'),
        ('ecoles', '0006_province_alter_ecole_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='province_affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ecoles.province', verbose_name="Province d'affectation"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('INSPECTEUR', 'Inspecteur'), ('AGENT', 'Agent'), ('ENSEIGNANT', 'Enseignant'), ('PARENT', 'Parent'), ('PROVED', 'Directeur Provincial')], default='ADMIN', max_length=20),
        ),
    ]
