# Generated by Django 5.0.2 on 2026-08-02 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_utilisateur_province_affectation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reset_code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('PASSWORD_RESET', 'Réinitialisation mot de passe'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('LOGIN_FAILED', 'Échec de connexion')], max_length=20)),
                ('model_name', models.CharField(blank=True, choices=[('Utilisateur', 'Utilisateur'), ('Ecole', 'École'), ('Province', 'Province'), ('Niveau', 'Niveau'), ('Classe', 'Classe'), ('Domaine', 'Domaine'), ('Cours', 'Cours'), ('Eleve', 'Élève'), ('EvaluationResultat', "Résultat d'évaluation"), ('Bulletin', 'Bulletin'), ('AnneeScolaire', 'Année scolaire')], max_length=50, null=True)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['utilisateur', 'timestamp'], name='accounts_au_utilisa_5e6801_idx'), models.Index(fields=['action', 'timestamp'], name='accounts_au_action_11cc52_idx'), models.Index(fields=['model_name', 'object_id'], name='accounts_au_model_n_76c60d_idx')],
            },
        ),
    ]
