# Generated by Django 5.0.2 on 2026-08-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_utilisateur_reset_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='eleves_associes',
        ),
    ]
