# Generated by Django 5.0.2 on 2026-08-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_utilisateur_eleves_associes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('INSPECTEUR', 'Inspecteur'), ('AGENT', 'Agent'), ('ENSEIGNANT', 'Enseignant'), ('PARENT', 'Parent'), ('PROVED', 'Directeur Provincial'), ('EDITOR', 'Éditeur')], default='ADMIN', max_length=20),
        ),
    ]
