# Generated by Django 5.0.2 on 2026-08-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
    ]
